# Marks all issues that do not receive activity stale starting 2022
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '24 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue seems stale. Please react to show this is still important.'
        stale-pr-message: 'This PR seems stale. Please react to show this is still important.'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
        start-date: '2022-01-01'
        exempt-all-milestones: true
